// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFx7j_i5dJYBs8yEMiTXAHsez8aJ0qcBs',
    appId: '1:923749045762:web:25f5a6b93e53221b46391b',
    messagingSenderId: '923749045762',
    projectId: 'jewelry-app-8afec',
    authDomain: 'jewelry-app-8afec.firebaseapp.com',
    storageBucket: 'jewelry-app-8afec.firebasestorage.app',
    measurementId: 'G-WJTHZ0LMC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxYWK1fMfySt5srIrtnNtnMmXadbvPajM',
    appId: '1:923749045762:android:95d9a4e3e9f4fa5646391b',
    messagingSenderId: '923749045762',
    projectId: 'jewelry-app-8afec',
    storageBucket: 'jewelry-app-8afec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZWqqRufflmtP5EidEPrhxBa-5JnKo7w',
    appId: '1:923749045762:ios:7b02ce832f9ac60146391b',
    messagingSenderId: '923749045762',
    projectId: 'jewelry-app-8afec',
    storageBucket: 'jewelry-app-8afec.firebasestorage.app',
    iosBundleId: 'com.example.jeweleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZWqqRufflmtP5EidEPrhxBa-5JnKo7w',
    appId: '1:923749045762:ios:7b02ce832f9ac60146391b',
    messagingSenderId: '923749045762',
    projectId: 'jewelry-app-8afec',
    storageBucket: 'jewelry-app-8afec.firebasestorage.app',
    iosBundleId: 'com.example.jeweleryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFx7j_i5dJYBs8yEMiTXAHsez8aJ0qcBs',
    appId: '1:923749045762:web:b9e927da7f96f85a46391b',
    messagingSenderId: '923749045762',
    projectId: 'jewelry-app-8afec',
    authDomain: 'jewelry-app-8afec.firebaseapp.com',
    storageBucket: 'jewelry-app-8afec.firebasestorage.app',
    measurementId: 'G-ZSTC87DXDT',
  );

}